baseURL = "https://www.syam.work/"
title = "syam.work"
ignoreErrors = ["error-remote-getjson"]

[Params]
  description = "Syam's Portfolio!"
  [Params.Terminal]
  schema = "monokai"

  userName = "syam"
  pcName = "macbookpro"
  workDir = "about"
  profile = "me.txt"

  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 10 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  description = """
  Hey I'm Syam
  a product focused tech guy
  
  """

  [Params.Tree]
  use = true
  folderName = "about"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["work:furlenco", "/work/furlenco.md"],
    ["work:gsod'20", "/work/gsod20.md"],
    ["work:gsoc'19", "/work/gsoc19.md"],
    ["work:gsoc'18", "/work/gsoc18.md"],
    ["personal:entertainment", "/personal/entertainment.md"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
